id: P004171
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG4846
  title: གྲུབ་མཐའ་མཁས་པའི་ཡིད་འཕྲོག
  author: ''
  volumes:
    e312cd35b0744726beb36111f6503a2d:
      image_group_id: I1KG5128
      title: ''
      volume_number: 1
      total_pages: 94
      base_file: v001.txt
