id: P004171
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4846
  title: གྲུབ་མཐའ་མཁས་པའི་ཡིད་འཕྲོག
  author: ''
  volumes:
    e312cd35b0744726beb36111f6503a2d:
      image_group_id: I1KG5128
      title: ''
      volume_number: 1
      total_pages: 94
