id: IE6FB74D8
legacy_id: P004171
ocr_import_info:
  bdrc_scan_id: W1KG4846
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T10:09:10'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T16:49:06.778679+00:00'
last_modified: 2022-09-01 00:49:12.383576
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG4846
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG4846
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གྲུབ་མཐའ་མཁས་པའི་ཡིད་འཕྲོག
  author: སེར་སྨད་སྤོམ་ར་དགེ་བཤེས་ཡེ་ཤེས་དབང་ཕྱུག
statistics:
  ocr_word_mean_confidence_index: 0.8865284794041824
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I1KG5128:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5128
      total_pages: 94
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5128.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8865284794041824
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
